name: 'Project-Movie-Picture-Pipeline-CI-backend'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  linting-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: cd backend && pip install pipenv && pipenv install --dev

      - name: Lint code
        run: cd backend && pipenv run flake8

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: cd backend && pip install pipenv && pipenv install --dev
      - name: run test
        run: pipenv run pytest


  build-backend:
    needs: [linting-backend, test-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: cd backend && pip install pipenv && pipenv install --dev

      - name: build a docker
        run: cd backend && docker build . -t movie-backend 


