name: 'Project-Movie-Picture-Pipeline-CI-frontend'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  linting-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: ../frontend/package-lock.json

      - name: Install dependencies and run the linter
        run: cd frontend && npm install && npm run lint

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: ../frontend/package-lock.json

      - name: Install dependencies and run test
        run: cd frontend && npm install && npm run test

  build-frontend:
    needs: [linting-frontend, test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: ../frontend/package-lock.json

      - name: Install dependencies and run test
        run: cd frontend && npm install && npm run test

      - name: build a docker
        run: cd frontend && docker build . -t movie-frontend 


